### ISSUE TITLE
cambria-delete : Erreur dans le script 

### ISSUE THREAD

**Issue by aaaaadrien** [Cambria-Linux/cambria#10]
Le script cambria-delete appelle les commandes : 

`emerge --deselect  && emerge --depclean`

Je suppose que cambria-delete fonctionne comme cambria-install sur l'idée avec le nom du paquet en argument.

Il faudrait corriger donc le script ainsi : 

`emerge --deselect $1 && emerge --depclean`

Je n'ai pas trouvé la source du script pour faire un PR

**Comment by Skythrew** [comment]
Effectivement, il y a bien une erreur dans le script. En fait, cambria-delete, comme tous les scripts et les alias personnalisés de la distribution, est généré à la post-installation par cambria-center. Il manquait donc un caractère d'échappement pour générer correctement le fichier 👍 Merci du retour 🙂
