### ISSUE TITLE
Ajout de paquet : gentoolkit

### ISSUE THREAD

**Issue by aaaaadrien** [Cambria-Linux/cambria#11]
Les commandes equery , eclean-dist, eclean-pkg et revdep-rebuild, utiles par moment pour de la recherche avancée ou du nettoyage ne sont pas dispo.

Est-il possible d'installer app-portage/gentoolkit ?

**Comment by camini** [comment]
Ce sera ajouté pour la prochaine release

**Comment by camini** [comment]
Done
