### ISSUE TITLE
Ajouter un suivi lors de la copie (barre de progression) 

### ISSUE THREAD

**Issue by aaaaadrien** [Cambria-Linux/cambria#12]
Prérequis : 

Ajouter dans l'ISO de Gentoo l'outil pv ( sys-apps/pv )

Modifier le script d'install  : 
`# Copy stage archive`
`cp \$FILE /mnt/gentoo`

`# Extract stage archive`
`cd /mnt/gentoo`
`tar xpf \$FILE --xattrs-include='*.*' --numeric-owner`
par
`pv $FILE | tar -xJpf -  --xattrs-include='*.*' --numeric-owner -C /tmp/gentoo/`

De fait, la ligne plus loin sera inutile :  
`rm /mnt/gentoo/\$(basename \$FILE)`

**Comment by Skythrew** [comment]
C'est fait ! :+1: Ce sera dans la prochaine version :smiley:
