### ISSUE TITLE
Problème lors de la sélection des partitions (erreur partition swap)

### ISSUE THREAD

**Issue by Firebleu** [Cambria-Linux/cambria#19]
Après avoir correctement créé les 3 partitions nécessaires, il semble qu'il y ait un problème lors de l'étape de sélection des partitions.

L'erreur en question est : "La partition SWAP ne peut pas être la même que la partition EFI."
J'ai refait la procédure plusieurs fois en m'assurant de sélectionner les bonnes partitions (la partition EFI et la partition SWAP que j'ai sélectionnées ne sont pas les mêmes), mais j'obtiens toujours la même erreur.

![image](https://github.com/Cambria-Linux/cambria/assets/89481193/ba3d6229-8836-4234-b784-a2c7318909f7)

**Comment by CorentinGAL** [comment]
Bonjour, 

J'ai eu aussi cette erreur, j'ai réussi a passer outre en changeant l'ordre de mes partions qui est le suivant : /dev/sda1 -> EFI System , /dev/sda2 -> Swap, /dev/sda3 -> Root Partition.

**Comment by Babilinx** [comment]
Il me faudrait la valeur des variables suivantes juste après le message d'erreur : `ROOT_PART`, `UEFI_PART` et `SWAP_PART` (`echo $<variable>`).

**Comment by Babilinx** [comment]
> Bonjour,
> 
> J'ai eu aussi cette erreur, j'ai réussi a passer outre en changeant l'ordre de mes partions qui est le suivant : /dev/sda1 -> EFI System , /dev/sda2 -> Swap, /dev/sda3 -> Root Partition.

C'est normal que ça marche car c'est ce qui est recomandé

**Comment by Skythrew** [comment]
Corrigé dans les nouvelles ISOs en cours d'upload :+1:
