### ISSUE TITLE
Problem encountered after installation (manual installation)

### ISSUE THREAD

**Issue by Firebleu** [Cambria-Linux/cambria#22]
Hello,

I'm interested in your easy way to install gentoo, so I gave it a try.

I'm running Cambria on a VM (wMWare) with 4 processor cores and 4096 MB of RAM.

I start the installation, choose the manual option and go through the steps. All goes well. I press the R button after the message telling me that the system is correctly installed.

I reboot and unfortunately can't connect (to access my desktop). All I can do is reinstall the system, as if it hadn't been installed.

Does anyone have a solution?

**Comment by Skythrew** [comment]
Hi 👋

Just some simple questions to identify more precisely the issue:
What version of Cambria are you installing (KDE or GNOME) ?

You're saying that you can't access your desktop. Is it a login issue on the display manager ? If not, do you have a screenshot of any step that may leads to the issue ?

Thank you for your feedback 🙂

**Comment by Firebleu** [comment]
Hello,

I'm using the latest version (Gnome edition) that you've put online.

I find myself on the terminal to install the
![Capture d'écran 2023-09-16 134655](https://github.com/Cambria-Linux/cambria/assets/89481193/fd3008e2-1564-4f02-897b-163fc766cb30)

**Comment by Firebleu** [comment]
I'd like to point out that I've redone the insllation (for the second time in a row) but I'm still having the same problem.

**Comment by Skythrew** [comment]
You're probably booting on the ISO again and again because the boot option for Cambria may not be the first available in your UEFI. You should go to your VM UEFI boot menu to check if there's a `gentoo` boot option there 👍

**Comment by Firebleu** [comment]
Ok thanks ! I just need to find the button !

**Comment by Babilinx** [comment]
Or you can just remove the boot option from the VM's settings. Pretty simple on virt-manager but i don't know on others

**Comment by Firebleu** [comment]
Ok thanks !

**Comment by Firebleu** [comment]
Thanks you it worked !

**Comment by Skythrew** [comment]
You're welcome :smiley:
