### ISSUE TITLE
Practical question for my information

### ISSUE THREAD

**Issue by Firebleu** [Cambria-Linux/cambria#24]
Hello,

I have a question for you.
I noticed a pretty neat "post install" tool.
I'd just like a recommendation.
For step 1 entitled "Build jobs", I would have liked to know how many "number of MAKE jobs" (voir photo), I should put for my configuration. 
I'm going to use this laptop every day to do all my daily tasks.

I've taken the GNOME version and here's my pc's configuration:
Device name Firebleu
Processor AMD Ryzen 7 5800H with Radeon Graphics 3.20GHz (8-core processor)  
Installed RAM 16.0 GB
System type 64-bit operating system, x64 processor

![IMG_3455](https://github.com/Cambria-Linux/cambria/assets/89481193/d18a085b-a779-4199-b442-8e7bc04b278c)

[I'm asking this because some people say that some software requires 2 to 3 gigabytes of ram per compilation job. They therefore recommend an 8-core processor and 8 gigabytes of ram, so choose option 4. But for my part, I have 16 gigabytes of ram, so I don't know which options to choose.]

**Comment by Babilinx** [comment]
Hello, it depends on the swap space. I also recomend you to use zram with the highest prority to have faster speeds. If you get `zram = ramsize` and `swapsize > 8` you can set make jobs to the maximum number of threads of your CPU - in this case 16. Set Portage (emerge) jobs to one if doing so.

**Comment by Firebleu** [comment]
All right, thanks!

So if I have a 9 gigabyte SWAP partition, I can set make jobs to the maximum?

**Comment by Babilinx** [comment]
If you setup zram, yes tou can, else the recomended max is 12

**Comment by Firebleu** [comment]
Do I have to setup zram after installation or is there a way to do it with your automatic setup?

**Comment by Babilinx** [comment]
You have to do it manualy after the install. It is planed to be in the install in the future.

**Comment by Firebleu** [comment]
All right, thanks!

Just a recap:

- without zram :
Swap = 9 gigabytes 
Make jobs = 12
Portage (emerge) jobs = 1

With zram :
Swap = 9 gigabytes 
Make jobs = 32
Portage (emerge) jobs = 1

Is this correct?

**Comment by Babilinx** [comment]
The first yes, for the second, it is 16 make jobs

**Comment by Firebleu** [comment]
Ok thanks !
